### PR TITLE
Pop overly large keys to avoid file length limit

### PR DESCRIPTION
**Pull request by akmiller01**

### CODE REVIEW

**Comment by andylolz** [comment]
Right, yes – It looks as though this file is the culprit:
https://iatiregistry.org/dataset/unhabitat-activity

More details here:
https://github.com/codeforIATI/iati-data-bugtracker/issues/8

**Comment by akmiller01** [comment]
Thanks, @andylolz . Added in a quick comment explanation.

**Comment by andylolz** [comment]
Perfect – thank you!

**Comment by akmiller01** [comment]
Included as part of https://github.com/IATI/IATI-Dashboard/commit/de9130e3533e0bf41e60e99d7f754302ec1b8b3b

**Pull request closed without merging**
