### PR TITLE
Fix timeliness table yield

### PR DESCRIPTION
**Pull request by samuele-mattiuzzo**
Issue raised in this ticket (https://iati.zendesk.com/agent/tickets/7675).

We need to make sure this change has not affected anything else

### CODE REVIEW

**Comment by samuele-mattiuzzo** [comment]
This has been deployed to dev, that will be regenerated tomorrow morning, so on Monday we can assess the output on a simil-live environment

**Comment by andylolz** [comment]
> Issue raised in this ticket (https://iati.zendesk.com/agent/tickets/7675).

What’s the issue here? I think this change will result in the timeliness table showing the current month twice, and only going back 11 months instead of twelve. I guess this isn’t the desired goal.

**Comment by samuele-mattiuzzo** [comment]
> I guess UNHCR should fall in the window of “publishers of three months or more”, and since they have published in three of the last three months, I guess they should be showing as monthly. Is that right?

correct, there's an issue with UNHCR's first publication date (according to the dashboard is 2018-09-07) and when the annual vs monthly is calculated (2018-09-01), making UNHCR an annual publisher rather than monthly, just by a 6 days offset. I have checked and dec appears twice for me as well, I don't know how I've missed it, thanks

**Comment by stevieflow** [comment]
--> @rory09

**Comment by andylolz** [comment]
In case it’s useful, here’s a diff showing how the timeliness frequency measure for all organisations is affected by this PR: https://gist.github.com/andylolz/7e18dc25b9ebde5c9368aa1d2ec17a59

**Comment by samuele-mattiuzzo** [comment]
for the record, this is just a test and I did create a PR with the purpose of exploring various options, rather than "here's the fix, merge it and deploy it straight away"

**Comment by andylolz** [comment]
> for the record, this is just a test and I did create a PR with the purpose of exploring various options, rather than "here's the fix, merge it and deploy it straight away"

Sure – understood.

> correct, there's an issue with UNHCR's first publication date (according to the dashboard is 2018-09-07) and when the annual vs monthly is calculated (2018-09-01), making UNHCR an annual publisher rather than monthly, just by a 6 days offset.

Yes! So I think they’re hitting this bit of code: https://github.com/IATI/IATI-Dashboard/blob/a5e8c4023b7e4de0b14a209df6cf9d58a689c9c8/timeliness.py#L90-L93

…i.e. they’re currently being considered a publisher of fewer than three months.

I guess this might relate to what the “full months” wording in the methodology is trying to capture. Even using full months, they’ve been publishing for more than 3 months – that’s just an issue with using the start of the month as the reference, rather than today’s day of the month. Presumably today’s day wasn’t used because months have differing numbers of days.

**Comment by andylolz** [comment]
I’ve had a go with #526. Note that that’s also for the purpose of exploring various options! I’m not totally sold on it myself.

Worth also noting that the methodology does explicitly say:

> The current month is also displayed for informational purposes, but is not used in the assessment.

**Comment by samuele-mattiuzzo** [comment]
discarding this PR as @andylolz solution is a bit more precise, counting the months from today's date rather than using "some months ago starting from the first day of that amount of months ago" sort of logic

**Pull request closed without merging**
