### PR TITLE
Remove coverage columns and replace coverage page with new copy

### PR DESCRIPTION
**Pull request by samuele-mattiuzzo**

### CODE REVIEW

**Comment by samuele-mattiuzzo** [comment]
Please read https://github.com/IATI/IATI-Dashboard/issues/514#issuecomment-423949401 before merging

**Comment by andylolz** [comment]
I wonder if it’s generally preferable to link to http://reference.iatistandard.org/organisation-standard/iati-organisations/iati-organisation/total-expenditure/ rather than http://reference.iatistandard.org/203/organisation-standard/iati-organisations/iati-organisation/total-expenditure/ ? (i.e. link to latest version of the standard, rather than v2.03 specifically).

**Comment by samuele-mattiuzzo** [comment]
@andylolz it makes sense and will discuss this internally, although I suppose by the time the coverage page gets reinstated, we'd still be on 2.03 and that wall of text will not be re-replaced by the actual coverage table, so as a temporary solution the direct link to 2.03 works as well

**Comment by Ocre42** [comment]
Ran it on our dev droplet, there's some issues whilst running `make_csv.py`
```
LOG: 2018-10-02 01:07:16 - Running make_csv.py
Traceback (most recent call last):
  File "make_csv.py", line 151, in <module>
    row['coverage_adjustment'],
KeyError: 'coverage_adjustment'
```
It probably means that there's some changes to be done on `make_html.py` as well, so keep that in mind.

**Comment by samuele-mattiuzzo** [comment]
Resuming this, will fix it :)

**Comment by samuele-mattiuzzo** [comment]
`gen_html.py` does not require further changes as we're not removing the coverage page - the whole purpose of this PR is to instead replace it with a graceful deprecation message.

**Pull request merged**
